import{S as g,a as b,i as m}from"./assets/vendor-56025df1.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const d=document.querySelector(".search-input"),S=document.querySelector(".search-btn"),n=document.querySelector(".gallery");let u=1;const i={key:"41300766-2a2685b0426849001fa971f21",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:u},v={overlayOpacity:.8,captionsData:"alt",captionDelay:250};let c="https://pixabay.com/api/?";const q=new g(".gallery a",v),p=async(s,a)=>{await b.get(s).then(({data:o})=>{if(!o.hits[0]){m.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#FAFAFB",position:"topRight",iconUrl:"/img/bi_x-octagon.svg",iconColor:"#ffffff",maxWidth:432,messageSize:16}),document.querySelector(".load-more-btn")&&document.querySelector(".load-more-btn").remove(),n.innerHTML="";return}const r=Math.ceil(o.totalHits/i.per_page);if(u===r){m.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",maxWidth:432,messageSize:16}),document.querySelector(".load-more-btn")&&document.querySelector(".load-more-btn").remove(),document.querySelector(".loader")&&document.querySelector(".loader").remove();return}L(o),window.scrollBy({top:a,behavior:"smooth"})}).catch(o=>{console.log(o)})};S.addEventListener("click",s=>{s.preventDefault(),document.querySelector(".loader")&&document.querySelector(".loader").remove(),document.querySelector(".load-more-btn")&&document.querySelector(".load-more-btn").remove(),n.insertAdjacentHTML("afterend",'<span class="loader"></span>'),u=1,i.q=d.value,c+=new URLSearchParams(i),d.value="",p(c,0)});const L=s=>{let a=s.hits.map(({webformatURL:r,largeImageURL:e,tags:t,likes:l,views:f,comments:h,downloads:y})=>`<li class="gallery-item">
        <a class="gallery-link" href=${e}>
          <img class="gallery-image" src=${r} data-source=${e} alt="${t}" width="360" height="200"/>
          <ul class="image-stats">
            <li class="stats-item"><h3 class="stat-title">Likes</h3><p class="stat-value">${l}</p></li>
            <li class="stats-item"><h3 class="stat-title">Views</h3><p class="stat-value">${f}</p></li>
            <li class="stats-item"><h3 class="stat-title">Comments</h3><p class="stat-value">${h}</p></li>
            <li class="stats-item"><h3 class="stat-title">Downloads</h3><p class="stat-value">${y}</p></li>
          </ul>  
          </a>
        </li>`).join(""),o='<button type="submit" class="load-more-btn">Load more</button>';document.querySelector(".loader").remove(),n.insertAdjacentHTML("beforeend",a),n.insertAdjacentHTML("afterend",o),document.querySelector(".load-more-btn").addEventListener("click",r=>{r.preventDefault(),document.querySelector(".load-more-btn").remove(),n.insertAdjacentHTML("afterend",'<span class="loader"></span>'),u+=1,c+=new URLSearchParams(i);const e=document.querySelector(".gallery-item").getBoundingClientRect().height*2;p(c,e)}),q.refresh()};
//# sourceMappingURL=commonHelpers.js.map
