import{S,a as q,i as p}from"./assets/vendor-cbff5fd8.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const w="/goit-js-hw-12/assets/bi_x-octagon-ddf7add7.svg",m=document.querySelector(".search-input"),$=document.querySelector(".search-form"),n=document.querySelector(".gallery");let i=1,d="",h=0;const l={key:"41300766-2a2685b0426849001fa971f21",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40},H={overlayOpacity:.8,captionsData:"alt",captionDelay:250};let f="https://pixabay.com/api/?";const M=new S(".gallery a",H),s=r=>{document.querySelector(r)&&document.querySelector(r).remove()},y=async(r,a)=>{await q.get(r).then(({data:t})=>{if(!t.totalHits){p.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#FAFAFB",position:"topRight",iconUrl:w,iconColor:"#ffffff",maxWidth:432,messageSize:16}),s(".loader"),s(".load-more-btn"),n.innerHTML="";return}if(h=Math.ceil(t.totalHits/l.per_page),t.hits.length<l.per_page||i===h){p.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",maxWidth:432,messageSize:16}),s(".loader"),s(".load-more-btn"),t.hits.length<=l.per_page&&t.hits.length>0&&g(t);return}g(t),window.scrollBy({top:a,behavior:"smooth"})}).catch(t=>{s(".loader"),console.log(t)})};$.addEventListener("submit",r=>{r.preventDefault(),m.value&&(n.innerHTML="",l.q=m.value,n.insertAdjacentHTML("afterend",'<span class="loader"></span>'),s(".load-more-btn"),i=1,d=f+new URLSearchParams(l)+`&page=${i}`,m.value="",y(d,0))});const g=r=>{let a=r.hits.reduce((t,{webformatURL:u,largeImageURL:e,tags:o,likes:c,views:b,comments:L,downloads:v})=>t+`<li class="gallery-item">
        <a class="gallery-link" href=${e}>
          <img class="gallery-image" src=${u} data-source=${e} alt="${o}" width="360" height="200"/>
          <ul class="image-stats">
            <li class="stats-item"><h3 class="stat-title">Likes</h3><p class="stat-value">${c}</p></li>
            <li class="stats-item"><h3 class="stat-title">Views</h3><p class="stat-value">${b}</p></li>
            <li class="stats-item"><h3 class="stat-title">Comments</h3><p class="stat-value">${L}</p></li>
            <li class="stats-item"><h3 class="stat-title">Downloads</h3><p class="stat-value">${v}</p></li>
          </ul>  
          </a>
        </li>`,"");s(".load-more-btn"),s(".loader"),n.insertAdjacentHTML("beforeend",a),n.insertAdjacentHTML("afterend",'<button type="submit" class="load-more-btn">Load more</button>'),document.querySelector(".load-more-btn").addEventListener("click",()=>{n.insertAdjacentHTML("afterend",'<span class="loader"></span>'),i+=1,d=f+new URLSearchParams(l)+`&page=${i}`;const t=document.querySelector(".gallery-item").getBoundingClientRect().height*2;y(d,t)}),(document.querySelector(".load-more-btn")&&r.hits.length>l.per_page||document.querySelector(".load-more-btn")&&i===h)&&s(".load-more-btn"),M.refresh()};
//# sourceMappingURL=commonHelpers.js.map
