import{S as v,a as L,i as m}from"./assets/vendor-cbff5fd8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const S="/goit-js-hw-12/assets/bi_x-octagon-ddf7add7.svg",d=document.querySelector(".search-input"),q=document.querySelector(".search-form"),i=document.querySelector(".gallery");let u=1,w="";const n={key:"41300766-2a2685b0426849001fa971f21",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40},H={overlayOpacity:.8,captionsData:"alt",captionDelay:250};let h="https://pixabay.com/api/?";const $=new v(".gallery a",H),a=o=>{document.querySelector(o)&&document.querySelector(o).remove()},f=async(o,r)=>{await L.get(o).then(({data:t})=>{if(t.hits.length===0){m.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#FAFAFB",position:"topRight",iconUrl:S,iconColor:"#ffffff",maxWidth:432,messageSize:16}),a(".loader"),a(".load-more-btn"),i.innerHTML="";return}const l=Math.ceil(t.totalHits/n.per_page);if(t.totalHits<=n.per_page||u===l){m.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",maxWidth:432,messageSize:16}),t.totalHits<=n.per_page&&p(t),a(".loader"),a(".load-more-btn");return}p(t),window.scrollBy({top:r,behavior:"smooth"})}).catch(t=>{a(".loader"),console.log(t)})};q.addEventListener("submit",o=>{o.preventDefault(),w!==d.value&&(i.innerHTML="",n.q=d.value),i.insertAdjacentHTML("afterend",'<span class="loader"></span>'),a(".loader"),a(".load-more-btn"),u=1;const r=h+new URLSearchParams(n)+`&page=${u}`;d.value="",f(r,0)});const p=o=>{let r=o.hits.reduce((t,{webformatURL:l,largeImageURL:e,tags:s,likes:c,views:g,comments:y,downloads:b})=>t+`<li class="gallery-item">
        <a class="gallery-link" href=${e}>
          <img class="gallery-image" src=${l} data-source=${e} alt="${s}" width="360" height="200"/>
          <ul class="image-stats">
            <li class="stats-item"><h3 class="stat-title">Likes</h3><p class="stat-value">${c}</p></li>
            <li class="stats-item"><h3 class="stat-title">Views</h3><p class="stat-value">${g}</p></li>
            <li class="stats-item"><h3 class="stat-title">Comments</h3><p class="stat-value">${y}</p></li>
            <li class="stats-item"><h3 class="stat-title">Downloads</h3><p class="stat-value">${b}</p></li>
          </ul>  
          </a>
        </li>`,"");a(".loader"),i.insertAdjacentHTML("beforeend",r),i.insertAdjacentHTML("afterend",'<button type="submit" class="load-more-btn">Load more</button>'),document.querySelector(".load-more-btn").addEventListener("click",t=>{t.preventDefault(),a(".load-more-btn"),i.insertAdjacentHTML("afterend",'<span class="loader"></span>'),u+=1;const l=h+new URLSearchParams(n)+`&page=${u}`,e=document.querySelector(".gallery-item").getBoundingClientRect().height*2;f(l,e)}),$.refresh()};
//# sourceMappingURL=commonHelpers.js.map
